- name: configure mysql server
  hosts: mysql
  become: yes  # remote server
  vars_files:
  - /var/expense/credentials_mysql.yaml #  ansible server
  roles:
  - mysql

  # all the script is placed in a proper order in the roles folder
  